syntax = "proto3";

package soar.application;
/*
Source 1: https://github.com/bufbuild/protobuf-language-spec/blob/main/language-spec.md
Source 2: https://protobuf.dev/getting-started/pythontutorial/
Style Guide, Language Guide (Proto 3) and Overview was referenced as well.
Source 3: https://www.geeksforgeeks.org/system-design/protocol-buffer-protobuf-in-system-design/
*/
message SensorReadings{
   int32 pressure_sensor_1 = 1;
   int32 pressure_sensor_2 = 2;
   
   int32 temp_reader = 3;
   
   bool valve_1_open = 4;
   bool valve_2_open = 5;
   bool valve_3_open = 6;
   bool valve_4_open = 7;
}
